### ISSUE TITLE
Upload Exception

### ISSUE THREAD

**Issue by abhimanyubabbar** [Decentrify/GVoD#4]
Unable to upload multiple videos whose cumulative size is greater than  4 gb.

---

ERROR [2015-09-08 11:31:11,221] se.kth.ws.dy.DYWSLauncher: exception:{} shutting down
! java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
! at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:859) ~[na:1.7.0_80]
! at se.sics.p2ptoolbox.util.managedStore.RMemMapFile.<init>(RMemMapFile.java:38) ~[dy_ws.jar:na]
! at se.sics.p2ptoolbox.util.managedStore.StorageFactory.getExistingFile(StorageFactory.java:31) ~[dy_ws.jar:na]
! at se.sics.p2ptoolbox.util.managedStore.StorageMngrFactory.getCompleteFileMngr(StorageMngrFactory.java:44) ~[dy_ws.jar:na]
! at se.sics.gvod.core.VoDComp.getUploadVideoMngrs(VoDComp.java:394) ~[dy_ws.jar:na]
! at se.sics.gvod.core.VoDComp.startUpload(VoDComp.java:292) ~[dy_ws.jar:na]
! at se.sics.gvod.core.VoDComp.access$800(VoDComp.java:83) ~[dy_ws.jar:na]
! at se.sics.gvod.core.VoDComp$4.handle(VoDComp.java:225) ~[dy_ws.jar:na]
! at se.sics.gvod.core.VoDComp$4.handle(VoDComp.java:211) ~[dy_ws.jar:na]
! at se.sics.kompics.JavaComponent.executeEvent(JavaComponent.java:365) [dy_ws.jar:na]
! at se.sics.kompics.JavaComponent.execute(JavaComponent.java:309) [dy_ws.jar:na]
! at se.sics.kompics.Scheduler.executeComponent(Scheduler.java:15) [dy_ws.jar:na]
! at se.sics.kompics.scheduler.ThreadPoolScheduler.access$100(ThreadPoolScheduler.java:15) [dy_ws.jar:na]
! at se.sics.kompics.scheduler.ThreadPoolScheduler$1.run(ThreadPoolScheduler.java:35) [dy_ws.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
! at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

**Comment by abhimanyubabbar** [comment]
The map method in the FileChannelImpl class limits the value to Integer.MAX_VALUE even though the method contract accepts long value.

**Comment by abhimanyubabbar** [comment]
Some More Information

---

http://stackoverflow.com/questions/8076472/filechannel-map-integer-max-value-limit-error
